//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FLCompanion.rc
//
#define IDD_FLCOMPANION_DIALOG          102
#define IDD_SPEEDDELAYS_DIALOG          103
#define IDD_SYSTEMMAP_DIALOG            104
#define IDD_LOGDLG_DIALOG               105
#define IDD_BASEINFO_DIALOG             106
#define IDD_GOODSREPO_DIALOG            107
#define IDD_DYNECON_DIALOG              108
#define IDD_ABOUT_DIALOG                109
#define IDD_LIMITATIONS_DIALOG          110
#define IDD_MININGBASE_DIALOG           112
#define IDD_MODINFO_DIALOG              113
#define IDR_MAINFRAME                   128
#define IDR_TOOLMENU                    130
#define IDI_BACK_ARROW                  136
#define IDR_ACCELERATOR                 137
#define IDI_JUMP                        138
#define IDI_SWITCH_ARROW                139
#define TEXTFILE                        256
#define IDR_MYTEXTFILE                  101
#define IDC_BASE_COMBO                  1000
#define IDC_ROUTES                      1001
#define IDC_SYSTEM_COMBO                1002
#define IDC_BACK                        1003
#define IDC_ASTEROIDS_COMBO             1004
#define IDC_STRINGVALUE                 1005
#define IDC_SWITCH                      1005
#define IDC_BASENAME                    1006
#define IDC_FACTION                     1006
#define IDC_WAYPOINTS                   1007
#define IDC_DESTBASE_COMBO              1008
#define IDC_DESTSYSTEM_COMBO            1009
#define IDC_MAP                         1010
#define IDC_ROUTE_STATIC                1011
#define IDC_DESTFACTION                 1011
#define IDC_CARGO_SIZE                  1012
#define IDC_MAPNAME                     1012
#define IDC_SYSTEM_WAYPOINTS            1013
#define IDC_PRICE_ONE                   1013
#define IDC_PRICE_CUSTOM                1014
#define IDC_ENGINE_SPEED                1015
#define IDC_LANE_SPEED                  1016
#define IDC_JUMP_DELAY                  1017
#define IDC_LOG                         1017
#define IDC_BASEINFO                    1017
#define IDC_LANE_DELAY                  1018
#define IDC_BASE_DELAY                  1019
#define IDC_AVOIDLOCKED                 1021
#define IDC_MAPINFO                     1021
#define IDC_BUY_PRICE                   1025
#define IDC_AVOIDHOLES                  1025
#define IDC_SELL_PRICE                  1026
#define IDC_INVESTMENT_CHECK            1026
#define IDC_PERISHABLE                  1027
#define IDC_INVESTMENT                  1027
#define IDC_HOLE_DELAY                  1028
#define IDC_DISTANCE_CHECK              1028
#define IDC_AVOIDUNSTABLEHOLES          1029
#define IDC_GOODS_LIST                  1031
#define IDC_EQUIP_LIST                  1032
#define IDC_DISTANCE                    1032
#define IDC_DESCR                       1033
#define IDC_SHIP_LIST                   1034
#define IDC_KIND_COMBO                  1035
#define IDC_BASES_LIST                  1037
#define IDC_DEFAULT_PRICE               1038
#define IDC_SHOWSELL                    1039
#define IDC_SHOWALL                     1040
#define IDC_URL                         1042
#define IDC_STATUS                      1044
#define IDLOAD                          1045
#define IDC_WEBLINK                     1046
#define IDC_ABOUTTEXT                   1047
#define IDC_ABOUTICON                   1048
#define IDC_MINING                      1051
#define IDC_LOOT_STAT                   1052
#define IDC_MINING_SPEED                1054
#define IDC_MINING_TIME                 1055
#define IDC_AUTHORS                     1056
#define IDC_CUSTOM1                     1057
#define IDC_RADIO_DESCRIPTION           1058
#define IDC_RADIO_FLCWARNING            1059
#define IDC_JUMPS                       1059
#define IDC_TRANSPORT                   1060
#define IDC_DESTSYSTEM_LABEL            1060
#define IDC_DESTBASE_LABEL              1061
#define IDC_MINING_LABEL                1062
#define IDC_TRADEROUTES                 1063
#define IDC_TR_ADD                      1064
#define IDC_TR_REM                      1065
#define IDI_UP_ARROW                    1066
#define IDC_MFCMENUBUTTON1              1066
#define IDI_DOWN_ARROW                  1067
#define IDC_EDIT1                       1067
#define IDC_MINCSU                      1068
#define IDC_FRAME_Systems               1069
#define IDC_SYSTEMS_LIST                1070
#define IDC_CHECK_ALL_SYSTEMS           1071
#define IDC_CLEAR_ALL_SYSTEMS           1072
#define IDC_FRAME_Factions              1073
#define IDC_FACTIONS_LIST               1074
#define IDC_CHECK_ALL_FACTIONS          1075
#define IDC_CLEAR_ALL_FACTIONS          1076
#define IDC_FRAME_Goods                 1077
#define IDC_CHECK_ALL_GOODS             1078
#define IDC_CLEAR_ALL_GOODS             1079
#define IDI_MAP                         1080
#define IDC_OPENMAP                     1081
#define IDC_DEFAULTSPEED                1082
#define IDC_MININGGOODS_PRICE           1083
#define IDC_SRCDEST_SWITCH              1084
#define IDC_FACTION_ID                  1085
#define IDR_CUSTOMBASEMENU              1086
#define IDM_MININGBASE                  1087
#define IDM_CUSTOMBASE                  1088
#define ID_DUMP_BASE_TIMES              32771
#define ID_BASE_INFO                    32772
#define ID_GOODS_REPO                   32773
#define ID_ABOUT                        32777
#define ID_VISIT_FORUM                  32780
#define ID_VERSION_HISTORY              32781
#define ID_SET_FL_DIR                   32782
#define ID_NICKNAMES                    32786
#define ID_VISIT_WEBSITE                32787
#define ID_LIMITATIONS                  32788
#define ID_SPEEDDELAYS                  32789
#define ID_SYSTEM_MAP                   32790
#define ID_GAME_LAUNCH                  32791
#define ID_MOD_INFO                     32792
#define ID_GAME_IMPORT_ABOUT            32798
#define ID_GAME_IMPORT_CHECKALL         32799
#define ID_GAME_IMPORT_PRICES           32800
#define ID_GAME_IMPORT_CREDITS          32801
#define ID_GAME_IMPORT_CARGOHOLD        32802
#define ID_VIEW_LOG                     32811
#define ID_CLIENTREFRESH                32812
#define IDC_AVOIDGATES                  32813
#define IDC_AVOIDLANES                  32814
#define ID_DUMP_SOLUTIONS               32815
#define IDC_JUMPTRADE_CHECK             32816
#define IDC_JUMPTRADE_TIME              32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
